# Generated by Django 5.0 on 2024-01-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
