# Generated by Django 5.0 on 2024-01-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookingdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='room_number',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
