# Generated by Django 5.0 on 2024-01-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingdetails_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='room_number',
        ),
    ]
