# Generated by Django 5.0 on 2024-01-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_bookingdetails_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('LGBTQ', 'LGBTQ')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='govt_id',
            field=models.CharField(choices=[('Aadhar card', 'Aadhar Card'), ('Passport', 'PassPort'), ('DL', 'Driving License'), ('VOter-Id', 'Voter-id'), ('Pan-card', 'Pan Card')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='govt_id_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='nationality',
            field=models.CharField(choices=[('indian', 'INDIAN'), ('non-indian', 'NON_INDIAN')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
