# Generated by Django 5.0 on 2024-01-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bookingdetails_gender_bookingdetails_govt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='no_adult',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='no_children',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
