# Generated by Django 5.0 on 2024-01-17 03:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='owner_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
