# Generated by Django 5.0 on 2024-01-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_remove_roomdata_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdata',
            name='owner_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
