# Generated by Django 5.0 on 2024-01-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_remove_roomdata_total_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField()),
                ('no_guest', models.IntegerField()),
                ('no_room', models.IntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
    ]
