# Generated by Django 5.0 on 2024-01-19 08:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_bookingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
