# Generated by Django 5.0 on 2024-01-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_bookingdetails_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='hotel_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
