# Generated by Django 5.0 on 2024-01-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_bookingdetails_hotel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookingdetails',
        ),
    ]
